server:
  port: 8091
  context-path: /gps

spring:
    datasource:
        name: GPS_DB
        url: jdbc:mysql://59.110.235.8:6033/GPS_DB?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&zeroDateTimeBehavior=convertToNull
        username: root
        password: Tom!@#$4321Jiang
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
   # session:
      #  store-type: REDIS
   # redis:
      #  host: localhost
      #  port: 8091

mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.lj.entity

#pagehelper分页插件
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql

redis:
    host: 127.0.0.1
    port: 6379
    timeout: 0
    database: 0
    pool:
      max-active: 8
      max-wait: -1
      max-idle: 8
      min-idle: 0
# 打印sql
logging:
  level:
    com.lj.gps.biz.mapper: DEBUG